name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore /p:TreatWarningsAsErrors=true
    - name: Build
      run: dotnet build --no-restore /p:TreatWarningsAsErrors=true
    - name: Run Tests
      run: dotnet test --no-build
  nupkg:
    name: Generate NuGet Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      name: Install Current .NET SDK
    - name: Generate NuGet Packages
      run: dotnet pack --configuration Release --output nupkg /p:TreatWarningsAsErrors=true
    - uses: actions/upload-artifact@v3
      if: success() && github.ref == 'refs/heads/main'
      with:
        name: nupkg
        path: nupkg/*
        retention-days: 1
